platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-alpine

inputs:
  - name: git-repo

outputs:
  - name: build

run:
  path: git-repo/ci/tasks/mvn-package.sh
  