platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-alpine

inputs:
  - name: employeemgmt-service

run:
  path: employeemgmt-service/ci/tasks/mvn-test.sh
  