resources:
  - name: git-repo
    type: git
    source:
      uri: ((github.url))
      branch: main
  
jobs:
  - name: test
    public: true
    plan:
      - get: git-repo
        trigger: true
      - task: mvn-test
        file: git-repo/ci/tasks/mvn-test.yml

  - name: package-publish
    public: true
    plan:
      - get: git-repo
        passed: [test]
        trigger: true
      - task: mvn-package
        file: git-repo/ci/tasks/mvn-package.yml
      - task: deploy
        file: git-repo/ci/tasks/deploy.yml
        